### PR TITLE
Release 1.0.6

### PR DESCRIPTION
**Pull request by delarosatrevin**
Few changes introduced in this release:

* Added support for Ctffind-4.1.13
* Fixed clean-up of temporary processing folders
* Fixed way to retrieve CTFTILT program
* Bumped version to 1.0.6 and centralized in PLUGIN_VERSION

### CODE REVIEW

**Comment by delarosatrevin** [comment]
@azazellochg Can you take a quick look at this before finally merging into master? Specially the CTFTILT part. I noticed that the binary does not longer come with ctffind (in 4.1.13). So I left as default 4.1.10 for it. In practice this will require an extra installed binary, which is not a big deal, but still a bit annoying that we could not have both from the same one.

**Comment by azazellochg** [comment]
ctftilt comes with ctffind3 only
Best regards,
Grigory

--------------------------------------------------------------------------------
Grigory Sharov, Ph.D.

MRC Laboratory of Molecular Biology,
Francis Crick Avenue,
Cambridge Biomedical Campus,
Cambridge CB2 0QH, UK.
tel. +44 (0) 1223 267542 <+44%201223%20267542>
e-mail: gsharov@mrc-lmb.cam.ac.uk

**Comment by delarosatrevin** [comment]
Hum...I had it under the bin of ctffind4-4.3.10, but not sure if I copied there....anyway, I just reverted the default to be again ctffind3.

**Comment by azazellochg** [comment]
We can copy it to ctffind 4 binary folder

**Comment by delarosatrevin** [comment]
Yep, that might be another solution...the problem is if people link to an existing ctffind4 version that does not contain it.

**Comment by azazellochg** [comment]
Nobody uses it anyway xD

**Comment by delarosatrevin** [comment]
Yep, so maybe we keep it as it is, without enlarging ctffind4 binary.

**Comment by azazellochg** [comment]
@delarosatrevin ctftilt never came together with ctffind4 binaries. Probably I create the archive manually to include it. I didnt create 4.1.13 tgz so it was not there.

**Comment by delarosatrevin** [comment]
It makes sense.

**Pull request merged**
